name: Build

on:
  push:
    branches:
      - "*"
    tags:
      - "*"

jobs:
  build:
    name: Build
    runs-on: "ubuntu-latest"
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        name: Setup java
        with:
          distribution: temurin
          java-version: "21"

      - name: Grant gradlew x permission
        run: "chmod +x gradlew"

      - name: Build
        run: "./gradlew build"

      - uses: softprops/action-gh-release@v2
        name: Upload release
        if: github.ref_type == 'tag'
        with:
          files: "app/build/outputs/apk/release/app-release-unsigned.apk"
